// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAuditPackages(t *testing.T) {
	t.Parallel()

	query := AuditPackages()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAuditPackagesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuditPackagesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AuditPackages().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuditPackagesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AuditPackageSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuditPackagesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AuditPackageExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AuditPackage exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AuditPackageExists to return true, but got false.")
	}
}

func testAuditPackagesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	auditPackageFound, err := FindAuditPackage(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if auditPackageFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAuditPackagesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AuditPackages().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAuditPackagesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AuditPackages().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAuditPackagesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	auditPackageOne := &AuditPackage{}
	auditPackageTwo := &AuditPackage{}
	if err = randomize.Struct(seed, auditPackageOne, auditPackageDBTypes, false, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}
	if err = randomize.Struct(seed, auditPackageTwo, auditPackageDBTypes, false, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = auditPackageOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = auditPackageTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AuditPackages().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAuditPackagesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	auditPackageOne := &AuditPackage{}
	auditPackageTwo := &AuditPackage{}
	if err = randomize.Struct(seed, auditPackageOne, auditPackageDBTypes, false, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}
	if err = randomize.Struct(seed, auditPackageTwo, auditPackageDBTypes, false, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = auditPackageOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = auditPackageTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func auditPackageBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func auditPackageAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditPackage) error {
	*o = AuditPackage{}
	return nil
}

func testAuditPackagesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AuditPackage{}
	o := &AuditPackage{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, auditPackageDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AuditPackage object: %s", err)
	}

	AddAuditPackageHook(boil.BeforeInsertHook, auditPackageBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	auditPackageBeforeInsertHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.AfterInsertHook, auditPackageAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	auditPackageAfterInsertHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.AfterSelectHook, auditPackageAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	auditPackageAfterSelectHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.BeforeUpdateHook, auditPackageBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	auditPackageBeforeUpdateHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.AfterUpdateHook, auditPackageAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	auditPackageAfterUpdateHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.BeforeDeleteHook, auditPackageBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	auditPackageBeforeDeleteHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.AfterDeleteHook, auditPackageAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	auditPackageAfterDeleteHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.BeforeUpsertHook, auditPackageBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	auditPackageBeforeUpsertHooks = []AuditPackageHook{}

	AddAuditPackageHook(boil.AfterUpsertHook, auditPackageAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	auditPackageAfterUpsertHooks = []AuditPackageHook{}
}

func testAuditPackagesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAuditPackagesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(auditPackageColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAuditPackageToOneOriginUsingOriginName(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AuditPackage
	var foreign Origin

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, originDBTypes, false, originColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Origin struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.Origin, foreign.Name)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.OriginName().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.Name, foreign.Name) {
		t.Errorf("want: %v, got %v", foreign.Name, check.Name)
	}

	slice := AuditPackageSlice{&local}
	if err = local.L.LoadOriginName(ctx, tx, false, (*[]*AuditPackage)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.OriginName == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.OriginName = nil
	if err = local.L.LoadOriginName(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.OriginName == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testAuditPackageToOneSetOpOriginUsingOriginName(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditPackage
	var b, c Origin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditPackageDBTypes, false, strmangle.SetComplement(auditPackagePrimaryKeyColumns, auditPackageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, originDBTypes, false, strmangle.SetComplement(originPrimaryKeyColumns, originColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, originDBTypes, false, strmangle.SetComplement(originPrimaryKeyColumns, originColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Origin{&b, &c} {
		err = a.SetOriginName(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.OriginName != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.OriginAP[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.Origin, x.Name) {
			t.Error("foreign key was wrong value", a.Origin)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Origin))
		reflect.Indirect(reflect.ValueOf(&a.Origin)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.Origin, x.Name) {
			t.Error("foreign key was wrong value", a.Origin, x.Name)
		}
	}
}

func testAuditPackageToOneRemoveOpOriginUsingOriginName(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditPackage
	var b Origin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditPackageDBTypes, false, strmangle.SetComplement(auditPackagePrimaryKeyColumns, auditPackageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, originDBTypes, false, strmangle.SetComplement(originPrimaryKeyColumns, originColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetOriginName(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveOriginName(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.OriginName().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.OriginName != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.Origin) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.OriginAP) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAuditPackagesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAuditPackagesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AuditPackageSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAuditPackagesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AuditPackages().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	auditPackageDBTypes = map[string]string{`ID`: `integer`, `Operation`: `enum.origin_package_operation('promote','demote')`, `Trigger`: `enum.package_channel_trigger('unknown','builder_ui','hab_client')`, `RequesterID`: `bigint`, `RequesterName`: `text`, `CreatedAt`: `timestamp with time zone`, `Origin`: `text`, `Channel`: `text`, `PackageIdent`: `text`}
	_                   = bytes.MinRead
)

func testAuditPackagesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(auditPackagePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(auditPackageColumns) == len(auditPackagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAuditPackagesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(auditPackageColumns) == len(auditPackagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AuditPackage{}
	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, auditPackageDBTypes, true, auditPackagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(auditPackageColumns, auditPackagePrimaryKeyColumns) {
		fields = auditPackageColumns
	} else {
		fields = strmangle.SetComplement(
			auditPackageColumns,
			auditPackagePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AuditPackageSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAuditPackagesUpsert(t *testing.T) {
	t.Parallel()

	if len(auditPackageColumns) == len(auditPackagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AuditPackage{}
	if err = randomize.Struct(seed, &o, auditPackageDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AuditPackage: %s", err)
	}

	count, err := AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, auditPackageDBTypes, false, auditPackagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuditPackage struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AuditPackage: %s", err)
	}

	count, err = AuditPackages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
