// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountTokens               string
	Accounts                    string
	AuditJobs                   string
	AuditPackage                string
	AuditPackageGroup           string
	BusyWorkers                 string
	GroupProjects               string
	Groups                      string
	Jobs                        string
	OriginChannelPackages       string
	OriginChannels              string
	OriginIntegrations          string
	OriginInvitations           string
	OriginMembers               string
	OriginPackages              string
	OriginPrivateEncryptionKeys string
	OriginProjectIntegrations   string
	OriginProjects              string
	OriginPublicEncryptionKeys  string
	OriginPublicKeys            string
	OriginSecretKeys            string
	OriginSecrets               string
	Origins                     string
}{
	AccountTokens:               "account_tokens",
	Accounts:                    "accounts",
	AuditJobs:                   "audit_jobs",
	AuditPackage:                "audit_package",
	AuditPackageGroup:           "audit_package_group",
	BusyWorkers:                 "busy_workers",
	GroupProjects:               "group_projects",
	Groups:                      "groups",
	Jobs:                        "jobs",
	OriginChannelPackages:       "origin_channel_packages",
	OriginChannels:              "origin_channels",
	OriginIntegrations:          "origin_integrations",
	OriginInvitations:           "origin_invitations",
	OriginMembers:               "origin_members",
	OriginPackages:              "origin_packages",
	OriginPrivateEncryptionKeys: "origin_private_encryption_keys",
	OriginProjectIntegrations:   "origin_project_integrations",
	OriginProjects:              "origin_projects",
	OriginPublicEncryptionKeys:  "origin_public_encryption_keys",
	OriginPublicKeys:            "origin_public_keys",
	OriginSecretKeys:            "origin_secret_keys",
	OriginSecrets:               "origin_secrets",
	Origins:                     "origins",
}
