// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOriginIntegrations(t *testing.T) {
	t.Parallel()

	query := OriginIntegrations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOriginIntegrationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOriginIntegrationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OriginIntegrations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOriginIntegrationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OriginIntegrationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOriginIntegrationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OriginIntegrationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if OriginIntegration exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OriginIntegrationExists to return true, but got false.")
	}
}

func testOriginIntegrationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	originIntegrationFound, err := FindOriginIntegration(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if originIntegrationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOriginIntegrationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OriginIntegrations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOriginIntegrationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OriginIntegrations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOriginIntegrationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	originIntegrationOne := &OriginIntegration{}
	originIntegrationTwo := &OriginIntegration{}
	if err = randomize.Struct(seed, originIntegrationOne, originIntegrationDBTypes, false, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}
	if err = randomize.Struct(seed, originIntegrationTwo, originIntegrationDBTypes, false, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = originIntegrationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = originIntegrationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OriginIntegrations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOriginIntegrationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	originIntegrationOne := &OriginIntegration{}
	originIntegrationTwo := &OriginIntegration{}
	if err = randomize.Struct(seed, originIntegrationOne, originIntegrationDBTypes, false, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}
	if err = randomize.Struct(seed, originIntegrationTwo, originIntegrationDBTypes, false, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = originIntegrationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = originIntegrationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func originIntegrationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func originIntegrationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OriginIntegration) error {
	*o = OriginIntegration{}
	return nil
}

func testOriginIntegrationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &OriginIntegration{}
	o := &OriginIntegration{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OriginIntegration object: %s", err)
	}

	AddOriginIntegrationHook(boil.BeforeInsertHook, originIntegrationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	originIntegrationBeforeInsertHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.AfterInsertHook, originIntegrationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	originIntegrationAfterInsertHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.AfterSelectHook, originIntegrationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	originIntegrationAfterSelectHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.BeforeUpdateHook, originIntegrationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	originIntegrationBeforeUpdateHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.AfterUpdateHook, originIntegrationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	originIntegrationAfterUpdateHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.BeforeDeleteHook, originIntegrationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	originIntegrationBeforeDeleteHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.AfterDeleteHook, originIntegrationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	originIntegrationAfterDeleteHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.BeforeUpsertHook, originIntegrationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	originIntegrationBeforeUpsertHooks = []OriginIntegrationHook{}

	AddOriginIntegrationHook(boil.AfterUpsertHook, originIntegrationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	originIntegrationAfterUpsertHooks = []OriginIntegrationHook{}
}

func testOriginIntegrationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOriginIntegrationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(originIntegrationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOriginIntegrationToManyIntegrationOriginProjectIntegrations(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OriginIntegration
	var b, c OriginProjectIntegration

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, originProjectIntegrationDBTypes, false, originProjectIntegrationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, originProjectIntegrationDBTypes, false, originProjectIntegrationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.IntegrationID = a.ID
	c.IntegrationID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.IntegrationOriginProjectIntegrations().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.IntegrationID == b.IntegrationID {
			bFound = true
		}
		if v.IntegrationID == c.IntegrationID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := OriginIntegrationSlice{&a}
	if err = a.L.LoadIntegrationOriginProjectIntegrations(ctx, tx, false, (*[]*OriginIntegration)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.IntegrationOriginProjectIntegrations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.IntegrationOriginProjectIntegrations = nil
	if err = a.L.LoadIntegrationOriginProjectIntegrations(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.IntegrationOriginProjectIntegrations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testOriginIntegrationToManyAddOpIntegrationOriginProjectIntegrations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OriginIntegration
	var b, c, d, e OriginProjectIntegration

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, originIntegrationDBTypes, false, strmangle.SetComplement(originIntegrationPrimaryKeyColumns, originIntegrationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*OriginProjectIntegration{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, originProjectIntegrationDBTypes, false, strmangle.SetComplement(originProjectIntegrationPrimaryKeyColumns, originProjectIntegrationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*OriginProjectIntegration{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddIntegrationOriginProjectIntegrations(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.IntegrationID {
			t.Error("foreign key was wrong value", a.ID, first.IntegrationID)
		}
		if a.ID != second.IntegrationID {
			t.Error("foreign key was wrong value", a.ID, second.IntegrationID)
		}

		if first.R.Integration != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Integration != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.IntegrationOriginProjectIntegrations[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.IntegrationOriginProjectIntegrations[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.IntegrationOriginProjectIntegrations().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testOriginIntegrationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOriginIntegrationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OriginIntegrationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOriginIntegrationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OriginIntegrations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	originIntegrationDBTypes = map[string]string{`ID`: `bigint`, `Origin`: `text`, `Integration`: `text`, `Name`: `text`, `Body`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                        = bytes.MinRead
)

func testOriginIntegrationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(originIntegrationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(originIntegrationColumns) == len(originIntegrationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOriginIntegrationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(originIntegrationColumns) == len(originIntegrationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OriginIntegration{}
	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, originIntegrationDBTypes, true, originIntegrationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(originIntegrationColumns, originIntegrationPrimaryKeyColumns) {
		fields = originIntegrationColumns
	} else {
		fields = strmangle.SetComplement(
			originIntegrationColumns,
			originIntegrationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OriginIntegrationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOriginIntegrationsUpsert(t *testing.T) {
	t.Parallel()

	if len(originIntegrationColumns) == len(originIntegrationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OriginIntegration{}
	if err = randomize.Struct(seed, &o, originIntegrationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OriginIntegration: %s", err)
	}

	count, err := OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, originIntegrationDBTypes, false, originIntegrationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OriginIntegration struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OriginIntegration: %s", err)
	}

	count, err = OriginIntegrations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
